@startuml
'https://plantuml.com/sequence-diagram

class Application{

+main()
}

class GsonConverter{



+deserializeJsonFile( String GeneralInfo)
+StringCutter( String InputString)
+FindItem( List<JsonItemClass> items, String SearchString)
+OutPutTime( JsonItemClass item)
}

class JsonItemClass{
-String name
-Double price
-int quantity



+getName()
+getPrice()
+getQuantity()

}
Application o->  GsonConverter
GsonConverter o-> JsonItemClass
@enduml