@startuml
'https://plantuml.com/sequence-diagram

class Application{
-GsonConverter
-JsonItemClass
-jsonconverter
-searchstring

main()
}

class GsonConverter{



deserializeJsonFile()
StringCutter()
FindItem()
OutPutTime()
}

class JsonItemClass{
-name
-price
-quantity



getName()
getPrice()
getQuantity()

}

@enduml