@startuml
'https://plantuml.com/sequence-diagram

class Application{

+main()
}

class WordFinder{



+ WordReplacer(String InputString)
+FileWriter(String InputString, String NewFileName)

}

Application o-> WordFinder
@enduml