@startuml
'https://plantuml.com/sequence-diagram

class Application{

+main()
}

class Person{
-String FirstName
-String LastName
-String Salary
-map<String,String> map

+GetMap()
+GetLastname()
+GetFirstName()
+GetSalary()
}

class BasicDataParser{


+OutPutTime(List<Person> myList)



}
Application o-> BasicDataParser
BasicDataParser o-> Person
@enduml