@startuml
'https://plantuml.com/sequence-diagram

class Application{
-scanner
-personSorter
-filereader
-personlist

main()
}

class person{
-First Name
-LastName
-map<String,String>

GetMap()
GetLastname()
GetFirstName()
}

class BasicDataParser{


Outputtime()



}
@enduml