@startuml
'https://plantuml.com/sequence-diagram

class Application{
-scanner
-personSorter
-filereader
-numnames

main()
}

class person{
-First Name
-LastName
-map<String,String>

GetMap()
GetLastname()
GetFirstName()
}

class personSorter{


Outputtime()
ListSorter()


}
@enduml