@startuml
'https://plantuml.com/sequence-diagram

class Application{

+main()
}

class Person{
-String FirstName
-String LastName
-map<String,String> map

+GetMap()
+GetLastname()
+GetFirstName()
}

class PersonSorter{


+SortPersonMapList(List<Person> myList)
+OutPutTime(List<Person> myList, int NumNames)
+FileWriter(String InputString)


}
 Application o-> PersonSorter
 PersonSorter o-> Person
@enduml