@startuml
'https://plantuml.com/sequence-diagram

class Application{

+main()
}

class WebsiteGenerator{
 -Scanner in
-String  inputString1;
 -String  inputString2;
 -String  inputString3;
 -String  inputString4;
 -String Pathname1
 -String Pathname
 -File file1


+InputTime()
+JsDirectoryMaker()
+CSSDirectoryMaker()
+HTMLDirectoryAndFileMaker()
}

Application o-> WebsiteGenerator
@enduml