@startuml
'https://plantuml.com/sequence-diagram

class Application{
main()
}

class WordFrequencyFinder{



WordFrequencyFinder()
WordFrequencyPrinter()
CreateSpecialString()
sortByValue()

}


@enduml